# Generated by Django 2.2 on 2019-04-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课 程', 'verbose_name_plural': '课 程'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '学员信息'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='qq',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='QQ号'),
        ),
    ]
