# Generated by Django 2.2 on 2019-04-30 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_auto_20190426_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.Customer', verbose_name='所咨询客户 '),
        ),
    ]
